#define CRTC_ADDR_REG 0x3D4
#define CRTC_DATA_REG 0x3D5
#define START_ADDR_H 0xC
#define START_ADDR_L 0xD
#define CURSOR_H 0xE
#define CURSOR_L 0xF
#define V_MEM_BASE 0xB8000
#define V_MEM_SIZE 0x8000//80*25模式，显存32KB
#define NR_CHARS_PER_LINE 80
#define NR_BYTES_PER_CHAR 2
#define NR_LINES_PER_SCREEN 25
#define NR_BYTES_PER_LINE (NR_CHARS_PER_LINE*NR_BYTES_PER_CHAR)
#define NR_BYTES_PER_SCREEN (NR_LINES_PER_SCREEN*NR_BYTES_PER_LINE)


/*p265*/
#define BACK_COLOR_MASK 0xFF00
#define BACK_COLOR_SHIFT 4
#define FORE_COLOR_MASK 0xFF
#define FORE_COLOR_SHIFT 0

/*P266*/
#define BLICK 0x08

#define BLACK_COLOR 0x00
#define BLUE_COLOR 0x01
#define GREEN_COLOR 0x02
#define RED_COLOR 0x04
#define WHITE_COLOR 0x07

/* #define DEFAULT_CHAR_COLOR 0x0F */
#define DEFAULT_BACK_COLOR 0x00
#define DEFAULT_FORE_COLOR 0x0F
#define DEFAULT_COLOR  ((DEFAULT_BACK_COLOR <<BACK_COLOR_SHIFT) |      \
    (DEFAULT_FORE_COLOR))
